# permissions for end users to edit manilashares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manilashare-editor-role
rules:
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares/status
  verbs:
  - get
