# permissions for end users to view manilashares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manilashare-viewer-role
rules:
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares/status
  verbs:
  - get
