# permissions for end users to view manilas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manila-viewer-role
rules:
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas/status
  verbs:
  - get
