---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keystone.openstack.org
  resources:
  - keystoneservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaapis/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilabackups/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilabackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaschedulers/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilaschedulers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilashares/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilavolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manila.openstack.org
  resources:
  - manilavolumes/finalizers
  verbs:
  - update
- apiGroups:
  - manila.openstack.org
  resources:
  - manilavolumes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mariadb.openstack.org
  resources:
  - mariadbdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role
  namespace: openstack
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
