apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: manila-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ManilaAPI is the Schema for the manilaapis API
      displayName: Manila API
      kind: ManilaAPI
      name: manilaapis.manila.openstack.org
      version: v1beta1
    - description: Manila is the Schema for the manilas API
      displayName: Manila
      kind: Manila
      name: manilas.manila.openstack.org
      version: v1beta1
    - description: ManilaScheduler is the Schema for the manilaschedulers API
      displayName: Manila Scheduler
      kind: ManilaScheduler
      name: manilaschedulers.manila.openstack.org
      version: v1beta1
    - description: ManilaShare is the Schema for the manilashares API
      displayName: Manila Share
      kind: ManilaShare
      name: manilashares.manila.openstack.org
      version: v1beta1
  description: manila
  displayName: manila
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - manila
  links:
  - name: Manila Operator
    url: https://manila-operator.domain
  maintainers:
  - email: fpantano@redhat.com
    name: fmount
  maturity: alpha
  provider:
    name: manila
  version: 0.0.0
