apiVersion: manila.openstack.org/v1beta1
kind: Manila
metadata:
  name: manila
  namespace: openstack
spec:
  serviceUser: manila
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  secret: osp-secret
  databaseUser: manila
  manilaAPI:
    replicas: 1
    containerImage: quay.io/tripleowallabycentos9/openstack-manila-api:current-tripleo
  manilaScheduler:
    replicas: 1
    containerImage: quay.io/tripleowallabycentos9/openstack-manila-scheduler:current-tripleo
  manilaShares:
    share1:
      containerImage: quay.io/tripleowallabycentos9/openstack-manila-share:current-tripleo
      replicas: 1
